#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"

#!/bin/bash

while IFS=: read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "User $userid's place is protected by the passcode $password."
    echo "More info about the user here: $userdesc"
done < /etc/passwd
#done < "$file"
