#!/usr/bin/env bash

file="/etc/passwd"

while IFS=: read -r username _ userid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
    echo
done < "$file"

