#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.

file="/etc/passwd"

#!/bin/bash

while IFS=: read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
#done < "$file"
#The user daemon is part of the 1 gang, lives in /usr/sbin and rides /usr/sbin/nologin. 1's place is protected by the passcode x, more info about the user here: daemon
