#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

file="/etc/passwd"
#!/bin/bash

while IFS=: read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userdesc"
done < "$file"
