#!/usr/bin/env bash
# write a Bash script that groups visitors by IP and HTTP status code, and displays this data.
#!/bin/bash

log_file="apache-access.log"

awk '{count[$1" "$9]++} END {for (key in count) {print count[key], key}}' "$log_file" | sort -rn
