#!/usr/bin/env bash
# write a Bash script that groups visitors by IP and HTTP status code, and displays this data.
#!/bin/bash

log_file="apache-access.log"

awk '{ print $1 " " $9}' "$log_file" | sort | uniq -c | sort -rn
