#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times.  Use until loop
counter=1
while [ $counter -le 20 ]
do
	echo $counter
	case $counter in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		
	esac
	((counter++))
done
