#!/usr/bin/env bash
#write a Write a Bash script that displays:The content of the current directory

LIST=$(ls)
for file in $LIST 
do 
	[ ! -f "$file" ] && continue
	grep ^"[[:digit:]]-" "$file" | cut -d "-" -f2
done
