#!/usr/bin/env bash
#write a Write a Bash script that displays:The content of the current directory

for file in *; do
    if [[ ! $file =~ ^\. ]]; then
        filename=$(echo "$file" | cut -d '-' -f2-)
        echo "$filename"
    fi
done

