#!/usr/bin/env bash
#Write Bash (init) script 11-manage_my_process that manages manage_my_process

PID_FILE="/var/run/my_process.pid"
MANAGE_MY_PROCESS_SCRIPT="manage_my_process"

start() {
    if [[ -f "$PID_FILE" ]]; then
        echo "manage_my_process is already started"
        exit 1
    fi

    ./"$MANAGE_MY_PROCESS_SCRIPT" &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [[ ! -f "$PID_FILE" ]]; then
        echo "manage_my_process is not running"
        exit 1
    fi

    pid=$(cat "$PID_FILE")
    kill "$pid"
    rm "$PID_FILE"
    echo "manage_my_process stopped"
}

restart() {
    if [[ ! -f "$PID_FILE" ]]; then
        echo "manage_my_process is not running"
        exit 1
    fi

    pid=$(cat "$PID_FILE")
    kill "$pid"
    "$MANAGE_MY_PROCESS_SCRIPT" &
    echo $! > "$PID_FILE"
    echo ./"manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_your_process {start|stop|restart}"
        exit 1
esac

